version: '3.7'
services:

    #PHP Service
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: app:latest
        container_name: app
        restart: unless-stopped
        tty: true
        networks:
            - app-network

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge

#Volumes
volumes:
    dbdata:
        driver: local
